### ISSUE TITLE
undefine is not defined

### ISSUE THREAD

**Issue by aa403210842** [mblarsen/mongoose-hidden#16]
# i found a  spelling mistake

### line 86 ~95
``` 
function getPath(obj, path) {
  let parts = path.split('.')
  while (parts.length) {
    obj = obj[parts.shift()]
    if (typeof obj !== 'object' && parts.length) {
      return undefine // here
    }
  }
  return obj
}
```

**Comment by mblarsen** [comment]
@aa403210842 strange, that part was covered by the tests. What environment are you running on?

**Comment by mblarsen** [comment]
@aa403210842 No I was mistaken. That case is not covered by the test. Can you give me an example of what caused it and I'll add a test case for it? (if not I'll figure it out.

https://coveralls.io/builds/9325729/source?filename=lib%2Fmongoose-hidden.js#L91

**Comment by mblarsen** [comment]
@aa403210842 tests covers that case now https://coveralls.io/builds/9329461/source?filename=lib%2Fmongoose-hidden.js#L91
