### ISSUE TITLE
undefine is not defined - error with mongoose-hidden

### ISSUE THREAD

**Issue by naran3434** [mblarsen/mongoose-hidden#24]
saving data using model, while trying to access the result data  i am receiving following error :

ReferenceError: undefine is not defined
    at getPath (/home/shreeya/Desktop/node/hitchahual/node_modules/mongoose-hidden/lib/mongoose-hidden.js:91:14)
    at /home/shreeya/Desktop/node/hitchahual/node_modules/mongoose-hidden/lib/mongoose-hidden.js:179:47
    at Array.forEach (native)
    at /home/shreeya/Desktop/node/hitchahual/node_modules/mongoose-hidden/lib/mongoose-hidden.js:172:15
    at model.Document.$toObject (/home/shreeya/Desktop/node/hitchahual/node_modules/mongoose/lib/document.js:2130:19)
    at model.Document.toJSON (/home/shreeya/Desktop/node/hitchahual/node_modules/mongoose/lib/document.js:2348:15)
    at Object.stringify (native)
    at stringify (/home/shreeya/Desktop/node/hitchahual/node_modules/express/lib/response.js:1064:12)
    at ServerResponse.json (/home/shreeya/Desktop/node/hitchahual/node_modules/express/lib/response.js:243:14)
    at /home/shreeya/Desktop/node/hitchahual/routes/mobile/driver.js:125:20
    at /home/shreeya/Desktop/node/hitchahual/node_modules/mongoose/lib/model.js:3408:16
    at /home/shreeya/Desktop/node/hitchahual/node_modules/mongoose/lib/document.js:2002:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Any support for this ?

Thanks in Advance.

**Comment by mblarsen** [comment]
Hi @naran3434 could you post the code that causes this?

**Comment by naran3434** [comment]
Hi @mblarsen kindly look at my code.

--framing array --

array = {
        first_name : data.first_name,
        last_name : data.last_name,
        email : data.email,
        password : data.password,
        number : {
            mobile : data.mobile,
            country_code : {
                code : data.country_code,
                country : data.country_short_code
            }
        },
        status : 0
    };

new DriverModel(array).save(function (err, result) {
        if (err) return res.send({err: err});
        return res.json({status:1, data: result, msg: 'success'});
    });

Here when if i try to access result variable or return it. i got the error.

Thanks

**Comment by mblarsen** [comment]
@naran3434 could you please add your schema as well + where you init the plugin AND please use code blocks to format your code above.

**Comment by naran3434** [comment]
Here is my full model

`var mongoose = require('mongoose');

var Schema = mongoose.Schema;

var mongooseHidden = require('mongoose-hidden')({defaultHidden: {password: true}});

var bcrypt = require('bcrypt'),
    SALT_WORK_FACTOR = 10;

var DriverSchema = new Schema({
    _location: {type: Schema.Types.ObjectId, ref: 'locations'},
    category: Schema.Types.Mixed,
    name: String,
    email: {
        type: String,
        required: true,
        unique: true
    },
    password: {type: String},
    address: Schema.Types.Mixed,
    identification: Schema.Types.Mixed,
    number: Schema.Types.Mixed,
    vehicle: {
        _type: {type: Schema.Types.ObjectId, ref: 'vehicles'},
        _maker: {type: Schema.Types.ObjectId, ref: 'makers'},
        _model: {type: Schema.Types.ObjectId, ref: 'models'},
        _year: String,
        number: String,
        air_conditioned: Number
    },
    documents: {
        driver: Schema.Types.Mixed,
        vehicle: Schema.Types.Mixed
    },
    status: Number,
    created_at: Date,
    updated_at: Date
});


DriverSchema.plugin(mongooseHidden);


DriverSchema.pre('save', function(next) {
    // get the current date
    var currentDate = new Date();

    var driver = this;
    // change the updated_at field to current date
    this.updated_at = currentDate;

    // if created_at doesn't exist, add to that field
    if (!driver.created_at)
        driver.created_at = currentDate;

    if (!driver.isModified('password')) return next();

    bcrypt.genSalt(SALT_WORK_FACTOR, function(err, salt) {
        if (err) return next(err);

        // hash the password along with our new salt
        bcrypt.hash(driver.password, salt, function(err, hash) {
            if (err) return next(err);

            // override the cleartext password with the hashed one
            driver.password = hash;
            next();
        });
    });

});

DriverSchema.methods.comparePassword = function(candidatePassword, cb) {
    bcrypt.compare(candidatePassword, this.password, function(err, isMatch) {
        if (err) return cb(err);
        cb(null, isMatch);
    });
};

var Driver = mongoose.model('drivers', DriverSchema);

module.exports = Driver;`

**Comment by mblarsen** [comment]
@naran3434 note that I did commit a possible fix already, but it has not been published yet. Could you please try it first?

An approach:

1. Delete `node_modules/mongoose-hidden`
2. Clone the repo `git clone https://github.com/mblarsen/mongoose-hidden.git node_modules/mongoose-hidden`
3. Run your app again.

**Comment by naran3434** [comment]
Sure @mblarsen

**Comment by naran3434** [comment]
Thank you @mblarsen. 
It's working as expected now.

**Comment by mblarsen** [comment]
Fixed by 	79099be

**Comment by mblarsen** [comment]
@naran3434 0.9.3 published on NPM thanks for the help.

**Comment by naran3434** [comment]
@mblarsen Thanks for the quick support.
