### ISSUE TITLE
Automatic 'id' virtual?

### ISSUE THREAD

**Issue by tommhuth** [mblarsen/mongoose-hidden#6]
Does this plugin, in addition to hiding `_id`, also add an `id` virtual? I have a simple model using this plugin, and regardless of what I do, i always end up with an `id` attribute.

**Comment by mblarsen** [comment]
@tommhuth this plugin doesn't hide `id` but by default when you run `toObject` or `toJSON` Mongoose will not include virtual properties of which `id` is one. See this section on how to include them and of course the plugin can be configured to hide virtual properties as well if needed.

https://github.com/mblarsen/mongoose-hidden#virtuals

**Comment by mblarsen** [comment]
@tommhuth just realized that I had misunderstood your question.

No, it doesn't add a virtual for `id`.
