### ISSUE TITLE
Any support for Typescript

### ISSUE THREAD

**Issue by iamchathu** [mblarsen/mongoose-hidden#67]
Currently there is no types definitions for this module for TypeScript. Any plans to add?

**Comment by mblarsen** [comment]
I don't use Typescript myself so I wouldn't be the best suited to add them. You are most welcome to make a PR for it.

**Comment by mblarsen** [comment]
TypeScript definitions was added to v1.6.2 by @marshalys

Fell free to extended them with types for options and what not
