### ISSUE TITLE
Node versions to support

### ISSUE THREAD

**Issue by mblarsen** [mblarsen/mongoose-hidden#86]
1. Should we follow Node LTS?
2. Should we update frequently
3. Does anyone use oooold node versions?

**Comment by Santinell** [comment]
1) As for me, I use only LTS. (maybe we can keep one outdated version like 8.x now)
2) If we follow Node.js plan you can update it once a year
3) ...

**Comment by mblarsen** [comment]
I was also thinking to follow whatever Mongoose is following.

**Comment by AlbertHambardzumyan** [comment]
Looks like mongoose still supports Node.js v4, [see](https://github.com/Automattic/mongoose/blob/master/package.json#L81).

This package is always integrated with mongoose and at first glance following whatever Mongoose is following makes sense. However, Node.js v4 eol was in [2018-04-30](https://github.com/nodejs/Release#end-of-life-releases) and if someone is running production code on v4 then they definitely should consider upgrading it. 

As for me, we should follow [Node.js release schedule](https://github.com/nodejs/Release#release-schedule) and support **>=10** for today

Also, let's consider 
- adding **engines** in **package.json** 
-  build with Node.js **>10** too, [see travis config](https://github.com/mblarsen/mongoose-hidden/blob/master/.travis.yml)

**Comment by mblarsen** [comment]
Good points @AlbertHambardzumyan 

> This package is always integrated with mongoose and at first glance following whatever Mongoose is following makes sense. However, Node.js v4 eol was in 2018-04-30 and if someone is running production code on v4 then they definitely should consider upgrading it.

Yeah and secondly they probably wont go back and add this plugin.

I'm leaning to @Santinell's suggestion of one outdated version of LTS and then tagging being clear in the changelog when a shift happens.

**Comment by AlbertHambardzumyan** [comment]
❤️
